#!/bin/bash

if [ $1 ]
	then
	 ARQUIVO=$1
	fi

cat $ARQUIVO | grep grande | awk '{print $4}' | sed 's/supergaleria="//g' | sed 's/>//g' | awk '{print "\"http://globoesporte.globo.com"$1}' | awk '{ system("wget " $1)}'

